section3: 3 - adjust website url

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -43,6 +43,25 @@ commands:
               && rm -rf /var/cache/apk/*
               apk add --update ansible
               npm install pm2 -g
+
+  revert-migrations:
+    description: Revert the last migration if successfully run in the current workflow.
+    parameters:
+      workflow_id:
+        type: string 
+    steps:
+      - run:
+          name: Revert migrations
+          when: on_fail
+          command: |
+            SUCCESS=$(curl -H "token: 9193554c-fc6e-4701-be40-85335fa888fb" --request GET https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID})
+            if(( $SUCCESS==1 )); 
+            then
+              cd ~/project/backend
+              npm install
+              npm run migration:revert
+              exit 1
+            fi
             
 jobs:
   build-frontend:
@@ -330,7 +349,7 @@ jobs:
       - run:
           name: Frontend smoke test.
           command: |
-            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-eu-central-1.amazonaws.com/#/employees"
+            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.eu-central-1.amazonaws.com/#/employees"
             echo ${URL}
             if curl -s ${URL} | grep "Welcome"
             then
@@ -339,6 +358,44 @@ jobs:
               return 1
             fi
       #- destroy-environment
+      #- revert-migrations
+
+ # cloudfront-update:
+ #   docker:
+ #     - image: python:3.7-alpine3.11
+ #   steps:
+ #     - checkout
+ #     - install-dependencies
+ #     - run:
+ #         name: Update cloudfront distribution
+ #         command: |
+ #           aws cloudformation deploy \
+ #             --template-file .circleci/files/cloudfront.yml \
+ #             --stack-name InitialStack \
+ #             --parameter-overrides WorkflowID="udapeople-${CIRCLE_WORKFLOW_ID:0:7}" \
+ #             --tags project=udapeople
+      #- destroy-environment
+      #- revert-migrations 
+
+#cleanup:
+#    docker:
+#      - image: python:3.7-alpine3.11
+#    steps:
+#      - checkout
+#      - install-dependencies
+#      - run:
+#          name: Get old stack workflow id
+#          command: |
+            # your code here
+ #           export OldWorkflowID="the id here"
+ #           export STACKS=[] #put the list of stacks here
+ #     - run:
+ #         name: Remove old stacks and files
+ #         command: |
+ #           if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
+ #           then
+ #             # your code here
+ #           fi
 
 workflows:
   default:
@@ -355,6 +412,9 @@ workflows:
           requires: [build-backend]   
       - deploy-infrastructure:
           requires: [test-frontend, test-backend, analyze-frontend, analyze-backend]
+          filters:
+            branches:
+              only: [master]
       - configure-infrastructure:
           requires: [deploy-infrastructure]
       - run-migrations:
